{
  'model': 'microsoft/Phi-3-mini-4k-instruct',
  'served_model_name': None,
  'tokenizer': 'microsoft/Phi-3-mini-4k-instruct',
  'skip_tokenizer_init': False,
  'tokenizer_mode': 'auto',
  'trust_remote_code': False,
  'download_dir': None,
  'load_format': 'auto',
  'dtype': 'auto',
  'kv_cache_dtype': 'auto',
  'quantization_param_path': None,
  'seed': 0,
  'max_model_len': None,
  'worker_use_ray': False,
  'pipeline_parallel_size': 1,
  'tensor_parallel_size': 2,
  'max_parallel_loading_workers': None,
  'block_size': 16,
  'enable_prefix_caching': False,
  'use_v2_block_manager': False,
  'swap_space': 4,
  'gpu_memory_utilization': 0.8,
  'max_num_batched_tokens': None,
  'max_num_seqs': 256,
  'max_logprobs': 5,
  'disable_log_stats': False,
  'revision': None,
  'code_revision': None,
  'tokenizer_revision': None,
  'quantization': None,
  'enforce_eager': True,
  'max_context_len_to_capture': None,
  'max_seq_len_to_capture': 8192,
  'disable_custom_all_reduce': False,
  'tokenizer_pool_size': 0,
  'tokenizer_pool_type': 'ray',
  'tokenizer_pool_extra_config': None,
  'enable_lora': False,
  'max_loras': 1,
  'max_lora_rank': 16,
  'fully_sharded_loras': False,
  'lora_extra_vocab_size': 256,
  'max_cpu_loras': None,
  'device': 'auto',
  'ray_workers_use_nsight': False,
  'num_gpu_blocks_override': None,
  'num_lookahead_slots': 0,
  'model_loader_extra_config': None,
  'image_input_type': None,
  'image_token_id': None,
  'image_input_shape': None,
  'image_feature_size': None,
  'scheduler_delay_factor': 0.0,
  'enable_chunked_prefill': False,
  'guided_decoding_backend': 'outlines',
  'speculative_model': None,
  'num_speculative_tokens': None,
  'speculative_max_model_len': None,
  'ngram_prompt_lookup_max': None,
  'ngram_prompt_lookup_min': None,
  'engine_use_ray': False,
  'disable_log_requests': False,
  'max_log_len': None,
  'auto_quantized_fallback': True,
  'quant_type_preference': 'GPTQ',
  'has_txt2img': False,
  'has_tts': False
}