{
  host: None,
  port: 40000,
  uvicorn_log_level: info,
  allow_credentials: False,
  allowed_origins: [ * ],
  allowed_methods: [ * ],
  allowed_headers: [ * ],
  api_key: None,
  lora_modules: None,
  chat_template: None,
  response_role: assistant,
  ssl_keyfile: None,
  ssl_certfile: None,
  ssl_ca_certs: None,
  ssl_cert_reqs: 0,
  root_path: None,
  middleware: [ ],
  model: microsoft/Phi-3-mini-4k-instruct,
  tokenizer: None,
  skip_tokenizer_init: False,
  revision: None,
  code_revision: None,
  tokenizer_revision: None,
  tokenizer_mode: auto,
  trust_remote_code: False,
  download_dir: None,
  load_format: auto,
  dtype: auto,
  kv_cache_dtype: auto,
  quantization_param_path: None,
  max_model_len: None,
  guided_decoding_backend: outlines,
  worker_use_ray: False,
  pipeline_parallel_size: 1,
  tensor_parallel_size: 1,
  max_parallel_loading_workers: None,
  ray_workers_use_nsight: False,
  block_size: 16,
  enable_prefix_caching: False,
  use_v2_block_manager: False,
  num_lookahead_slots: 0,
  seed: 0,
  swap_space: 4,
  gpu_memory_utilization: 0.8,
  num_gpu_blocks_override: None,
  max_num_batched_tokens: None,
  max_num_seqs: 256,
  max_logprobs: 5,
  disable_log_stats: False,
  quantization: None,
  enforce_eager: True,
  max_context_len_to_capture: None,
  max_seq_len_to_capture: 8192,
  disable_custom_all_reduce: False,
  tokenizer_pool_size: 0,
  tokenizer_pool_type: ray,
  tokenizer_pool_extra_config: None,
  enable_lora: False,
  max_loras: 1,
  max_lora_rank: 16,
  lora_extra_vocab_size: 256,
  lora_dtype: auto,
  max_cpu_loras: None,
  fully_sharded_loras: False,
  device: auto,
  image_input_type: None,
  image_token_id: None,
  image_input_shape: None,
  image_feature_size: None,
  scheduler_delay_factor: 0.0,
  enable_chunked_prefill: False,
  speculative_model: None,
  num_speculative_tokens: None,
  speculative_max_model_len: None,
  ngram_prompt_lookup_max: None,
  ngram_prompt_lookup_min: None,
  model_loader_extra_config: None,
  served_model_name: None,
  engine_use_ray: False,
  disable_log_requests: False,
  max_log_len: None,
  auto_quantized_fallback: True,
  quant_type_preference: GPTQ,
  enable_tts: False,
  tts_model: None,
}
