name: Nvidia Docker Build and Push on Release

on:
  release:
    types: [published]

jobs:
  build-and-push-nvidia:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push NVIDIA image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.nvidia
          push: true
          tags: marcoastramind/pulsar-nvidia:${{ github.ref_name }},marcoastramind/pulsar-nvidia:latest


